name: hrnet
frames_in: 3
frames_out: 3
inp_height: 288
inp_width: 512
out_height: 288
out_width: 512
rgb_diff: False
out_scales: [0]
MODEL:
  EXTRA:
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS: ['*']
    STEM:
      INPLANES: 64
      STRIDES: [1,1]
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS: [1]
      NUM_CHANNELS: [32]
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS: [2,2]
      NUM_CHANNELS: [16,32]
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 1
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS: [2,2,2]
      NUM_CHANNELS: [16,32,64]
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 1
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS: [2,2,2,2]
      NUM_CHANNELS: [16,32,64,128]
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 0
      KERNEL_SIZE: []
      NUM_BASIC_BLOCKS: 2
  INIT_WEIGHTS: True

